[package]
name = "OutlawSky"
version = "0.4.0"
authors = ["Paul Fidika (paul@fidika.com)"]
published-at = "0xb064e31000b08724ebd94a605cc47a9e722ba09d3b52f201e1af79de063add3a" # testnet

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
SuiUtils = { local = "../../../packages/sui_utils" }
Ownership = { local = "../../../packages/ownership" }
Attach = { local = "../../../packages/attach" }
TransferSystem = { local = "../../../packages/transfer_system" }

[addresses]
outlaw_sky = "0xb064e31000b08724ebd94a605cc47a9e722ba09d3b52f201e1af79de063add3a"
